// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvhsefjbzpudnvsszgec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2aHNlZmpienB1ZG52c3N6Z2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNDUyNzksImV4cCI6MjA1MTgyMTI3OX0.QdcjBmXLR28hTYPq8l-QcgcA0FL6-MXxiTFMrdntMeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);